-- 코드를 입력하세요

SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE (ANIMAL_TYPE='Dog') AND ((NAME LIKE '%EL') OR (NAME LIKE 'EL%') OR (NAME LIKE '%EL%'))
ORDER BY NAME; # -> 'Elijah', 'Ella'


# SELECT ANIMAL_ID, NAME
# FROM ANIMAL_INS
# WHERE (ANIMAL_TYPE='Dog') AND (NAME IN (SELECT NAME FROM ANIMAL_INS WHERE NAME LIKE '%EL%'))
# ORDER BY NAME; # -> 'Elijah', 'Ella'