-- 코드를 입력하세요
# SELECT PRODUCT_ID, PRODUCT_NAME, PRODUCT_CD, CATEGORY, MAX(PRICE) AS PRICE
# FROM FOOD_PRODUCT

SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);


# SELECT * FROM employee WHERE salary = (SELECT MAX(salary) FROM employee);
